# strings.py

STRINGS = {
    'it': {
        'welcome': "ciao {name}! sono il tuo assistente finanziario. come posso aiutarti oggi?",
        'bill_reminder': "🔔 **promemoria scadenza!**\n\ndevi pagare: **{name}**\nimporto: **{amount}€**\nscadenza: {due_date}\n\nusa /scadenze per gestirla!",
        'subscription_renewed': "🔄 **abbonamento rinnovato!**\n\nabbiamo registrato il pagamento di **{amount}€** per **{name}**.",
        'session_expired': "sessione scaduta, riprova.",
        'save_confirm_msg': "✅ **salvato!**\n{amount}€ per {desc}{budget_info}",
        'monthly_spent_label': "💰 speso nel mese: {total}€",
        'budget_left_label': "💰 restano: {amount}€",
        'over_budget_alert': "🚨 **fuori budget!** (-{amount}€)",
        'save_error': "❌ errore salvataggio.",
        'ocr_saved_ok': "✅ spesa di {amount}€ salvata correttamente!",
        'bill_set_ok': "📅 **promemoria impostato!**\nti avviserò la mattina del {date}.",
        'sub_saved_ok': "✅ abbonamento a **{name}** salvato!",
        'sub_removed_ok': "🗑️ abbonamento rimosso dalle ricorrenze!",
        'deleted_ok': "🗑️ eliminato correttamente!",
        'bill_paid_ok': "✅ bolletta '{name}' segnata come pagata e aggiunta alle spese!",
        'no_expenses_cat': "nessuna spesa per {cat} questo mese.",
        'detail_label': "dettaglio",
        'total_label': "totale",
        'back_btn': "⬅️ torna alla lista",
        'reset_ok': "🧹 **database pulito!**",
        'confirm_sub_btn': "✅ registra abbonamento",
        'confirm_bill_btn': "✅ imposta promemoria",
        'sub_detected_msg': "💳 **nuovo abbonamento rilevato**\n\n📌 servizio: **{name}**\n💰 quota mensile: **{amount}€**\n🔄 rinnovo: ogni **giorno {day}** del mese\n\nvuoi registrarlo?",
        'bill_detected_msg': "📅 **nuova scadenza rilevata**\n\n📌 **{name}**\n💰 importo: **{amount}€**\n🗓️ scadenza: **{date}**\n\nvuoi un promemoria?",
        'ai_understood': "ecco cosa ho capito:",
        'budget_warn_over': "\n⚠️ **attenzione:** fuori budget di {amount}€!",
        'budget_residue': "\n💰 budget residuo: **{amount}€**",
        'transaction_preview': "💬 {ai_text}\n\n💰 **{amount}€** in {cat}\n📝 **cosa:** {desc}\n📅 totale categoria: {cat_total}€{budget_info}",
        'error_understand': "⚠️ non ho capito bene. riprova scrivendo più chiaramente.",
        'no_expenses_month': "📭 nessuna spesa registrata per {month}.",
        'list_expenses_title': "📂 **spese di {month}**\nseleziona una categoria:",
        'parasite_report_alert': "📢 **check-up mensile abbonamenti!**\n\ncontrolla se usi ancora tutto quello che paghi...",
        'stats_header': "📊 **report mensile**",
        'stats_total_spent': "💸 totale speso: **{total}€**",
        'stats_subs_focus': "🧛 **focus abbonamenti parassiti:**\npaghi **{count}** servizi per **{total}€/mese**.",
        'no_subs_active': "✅ non hai abbonamenti attivi.",
        'analyzing_data': "📊 sto analizzando le tue spese...",
        'budget_remaining': "rimanenti: **{amount}€**",
        'over_budget': "⚠️ **fuori budget!**",
        'report_caption': "📈 **il tuo report mensile**",
        'chart_error': "i dati non sono sufficienti per il grafico.",
        'help_text': "🤖 **guida rapida:**\n\n💰 **registra spesa**: scrivi semplicemente '20 euro da OVS' o 'pizza 15€'.\n📊 **/report**: genera un grafico con l'analisi delle tue spese.\n💬 **chiacchiere**: puoi anche parlarmi normalmente, risponderò come un assistente!",
        'reset_warning': "⚠️ **attenzione!**\nsei sicuro di voler cancellare tutte le spese di questo mese? questa azione non può essere annullata.",
        'confirm_reset_btn': "✅ sì, cancella tutto",
        'no_subs_hint': "📉 **non hai abbonamenti registrati.**\n\nprova a dirmi: 'abbonamento netflix 12.99 il giorno 20'",
        'budget_set_ok': "🎯 **budget mensile impostato:** {amount}€\nda ora il report ti mostrerà quanto ti resta!",
        'budget_usage': "💡 usa: `/setbudget [cifra]` (es: `/setbudget 500`)",
        'delete_usage': "💡 usa: `/cancella [nome]` (es: `/cancella pizza`)",
        'no_results': "❓ non ho trovato nulla per '{query}'.",
        'results_found': "🗑️ ho trovato {count} spese. quali vuoi eliminare?",
        'delete_amount_btn': "🗑️ elimina {amount}€",
        'generic_expense': "spesa",
        'voice_listening': "🎧 ascolto e trascrivo...",
        'voice_empty': "⚠️ non ho sentito nulla, riprova.",
        'voice_understood': "📝 ho capito: \"{text}\"",
        'voice_error': "⚠️ scusa, c'è stato un errore nel processare l'audio.",
        'ocr_processing': "📸 sto leggendo lo scontrino...",
        'ocr_error': "❌ non sono riuscito a leggere lo scontrino.",
        'confirm_btn': "✅ conferma e salva",
        'cancel_btn': "🗑️ elimina",
        'ocr_success_msg': "✅ **scontrino analizzato**\n\n💰 importo: **{amount}€**\n🛒 negozio: {merchant}\n📁 categoria: {category}\n📅 data: {date}\n\nvuoi salvare questa spesa?",
        'no_subs': "📉 non hai abbonamenti registrati nel database.",
        'subs_title': "💳 **i tuoi abbonamenti attivi:**",
        'day_label': "giorno",
        'monthly_total_label': "💸 totale mensile: **{total}€**",
        'yearly_impact_label': "📅 impatto annuale: **{total}€**",
        'delete_btn': "🗑️ elimina {name}",
        'no_bills': "✨ non hai scadenze pendenti al momento!",
        'bills_title': "🗓️ **le tue scadenze attive:**",
        'delete_btn': "🗑️ elimina {name}",
        'delete_simple_btn': "🗑️ elimina",
        'pay_btn': "✅ pagata",
        'bill_reminder': "⏰ **promemoria scadenza!**\n\n📌 bolletta: **{name}**\n💰 importo: **{amount}€**\n\ncosa vuoi fare?",
        'inactivity_msg': "👀 **ehi, dove sei finito?**\nnon segno spese da 48 ore. hai acquisti da dirmi?",
        'weekly_report': "📅 **resoconto settimanale**\n\nfinora questo mese hai speso: **{total}€**",
        'subscription_renewed': "🔄 **rinnovo automatico!**\n\nho registrato **{name}** ({amount}€).",
        'confirm_transaction': "confermi {amount}€ in {category}?\n\n🏢 merchant: {merchant}\n📝 desc: {description}",
        'confirm_subscription': "vuoi registrare l'abbonamento {name} da {amount}€?",
        'saved': "✅ salvato correttamente!",
        'cancelled': "🗑️ operazione annullata.",
        'stats_msg': "📊 totale spese di questo mese: {total}€",
        'no_data': "nessun dato trovato per questo mese.",
        'budget_set': "✅ budget impostato a {amount}€",
        'help': "puoi scrivermi frasi come:\n- 'ho speso 10€ per un pranzo da luigi'\n- 'bolletta luce 80€'\n- 'report'\n- 'imposta budget a 500€'",
        'error': "ops, qualcosa è andato storto. riprova!",
        
    },
    'en': {
        'welcome': "hello {name}! i am your financial assistant. how can i help you today?",
        'bill_reminder': "🔔 **bill reminder!**\n\nyou have to pay: **{name}**\namount: **{amount}€**\ndue date: {due_date}\n\nuse /scadenze to manage it!",
        'subscription_renewed': "🔄 **subscription renewed!**\n\nwe recorded a payment of **{amount}€** for **{name}**.",
        'session_expired': "session expired, please try again.",
        'save_confirm_msg': "✅ **saved!**\n{amount}€ for {desc}{budget_info}",
        'monthly_spent_label': "💰 spent this month: {total}€",
        'budget_left_label': "💰 left: {amount}€",
        'over_budget_alert': "🚨 **over budget!** (-{amount}€)",
        'save_error': "❌ save error.",
        'ocr_saved_ok': "✅ expense of {amount}€ saved successfully!",
        'bill_set_ok': "📅 **reminder set!**\ni will notify you on the morning of {date}.",
        'sub_saved_ok': "✅ subscription to **{name}** saved!",
        'sub_removed_ok': "🗑️ subscription removed from recurrences!",
        'deleted_ok': "🗑️ successfully deleted!",
        'bill_paid_ok': "✅ bill '{name}' marked as paid and added to expenses!",
        'no_expenses_cat': "no expenses for {cat} this month.",
        'detail_label': "details",
        'total_label': "total",
        'back_btn': "⬅️ back to list",
        'reset_ok': "🧹 **database cleaned!**",
        'confirm_sub_btn': "✅ register subscription",
        'confirm_bill_btn': "✅ set reminder",
        'sub_detected_msg': "💳 **new subscription detected**\n\n📌 service: **{name}**\n💰 monthly fee: **{amount}€**\n🔄 renewal: every **day {day}** of the month\n\nwant to register it?",
        'bill_detected_msg': "📅 **new bill detected**\n\n📌 **{name}**\n💰 amount: **{amount}€**\n🗓️ due date: **{date}**\n\nwant a reminder?",
        'ai_understood': "here's what i understood:",
        'budget_warn_over': "\n⚠️ **warning:** over budget by {amount}€!",
        'budget_residue': "\n💰 remaining budget: **{amount}€**",
        'transaction_preview': "💬 {ai_text}\n\n💰 **{amount}€** in {cat}\n📝 **what:** {desc}\n📅 category total: {cat_total}€{budget_info}",
        'error_understand': "⚠️ i didn't quite catch that. please try writing more clearly.",
        'no_expenses_month': "📭 no expenses recorded for {month}.",
        'list_expenses_title': "📂 **expenses for {month}**\nselect a category:",
        'parasite_report_alert': "📢 **monthly subscription check-up!**\n\ncheck if you are still using everything you pay for...",
        'stats_header': "📊 **monthly report**",
        'stats_total_spent': "💸 total spent: **{total}€**",
        'stats_subs_focus': "🧛 **vampire subs focus:**\nyou pay for **{count}** services for **{total}€/month**.",
        'no_subs_active': "✅ no active subscriptions detected.",
        'analyzing_data': "📊 analyzing your expenses...",
        'budget_remaining': "remaining: **{amount}€**",
        'over_budget': "⚠️ **over budget!**",
        'report_caption': "📈 **your monthly report**",
        'chart_error': "not enough data for the chart.",
        'help_text': "🤖 **quick guide:**\n\n💰 **record expense**: just write '20 dollars at OVS' or 'pizza 15€'.\n📊 **/report**: generates a chart with your expense analysis.\n💬 **chat**: you can talk to me normally, i will respond as an assistant!",
        'reset_warning': "⚠️ **warning!**\nare you sure you want to delete all expenses for this month? this action cannot be undone.",
        'confirm_reset_btn': "✅ yes, delete everything",
        'no_subs_hint': "📉 **no subscriptions registered.**\n\ntry telling me: 'netflix subscription 12.99 on day 20'",
        'budget_set_ok': "🎯 **monthly budget set:** {amount}€\nfrom now on the report will show you how much is left!",
        'budget_usage': "💡 use: `/setbudget [amount]` (e.g.: `/setbudget 500`)",
        'delete_usage': "💡 use: `/delete [name]` (e.g.: `/delete pizza`)",
        'no_results': "❓ i couldn't find anything for '{query}'.",
        'results_found': "🗑️ i found {count} expenses. which ones do you want to delete?",
        'delete_amount_btn': "🗑️ delete {amount}€",
        'generic_expense': "expense",
        'voice_listening': "🎧 listening and transcribing...",
        'voice_empty': "⚠️ i didn't hear anything, please try again.",
        'voice_understood': "📝 i understood: \"{text}\"",
        'voice_error': "⚠️ sorry, there was an error processing the audio.",
        'ocr_processing': "📸 reading the receipt...",
        'ocr_error': "❌ i couldn't read the receipt.",
        'confirm_btn': "✅ confirm and save",
        'cancel_btn': "🗑️ delete",
        'ocr_success_msg': "✅ **receipt analyzed**\n\n💰 amount: **{amount}€**\n🛒 shop: {merchant}\n📁 category: {category}\n📅 date: {date}\n\ndo you want to save this expense?",
        'no_subs': "📉 no subscriptions registered in the database.",
        'subs_title': "💳 **your active subscriptions:**",
        'day_label': "day",
        'monthly_total_label': "💸 monthly total: **{total}€**",
        'yearly_impact_label': "📅 yearly impact: **{total}€**",
        'delete_btn': "🗑️ delete {name}",
        'no_bills': "✨ you have no pending bills at the moment!",
        'bills_title': "🗓️ **your active bills:**",
        'delete_simple_btn': "🗑️ delete",
        'pay_btn': "✅ paid",
        'bill_reminder': "⏰ **deadline reminder!**\n\n📌 bill: **{name}**\n💰 amount: **{amount}€**\n\nwhat do you want to do?",
        'inactivity_msg': "👀 **hey, where did you go?**\ni haven't recorded expenses in 48 hours. any new purchases to tell me about?",
        'weekly_report': "📅 **weekly summary**\n\nso far this month you have spent: **{total}€**",
        'subscription_renewed': "🔄 **automatic renewal!**\n\ni have recorded **{name}** ({amount}€).",
        'confirm_transaction': "confirm {amount}€ in {category}?\n\n🏢 merchant: {merchant}\n📝 desc: {description}",
        'confirm_subscription': "do you want to register the subscription {name} for {amount}€?",
        'saved': "✅ saved successfully!",
        'cancelled': "🗑️ operation cancelled.",
        'stats_msg': "📊 total expenses for this month: {total}€",
        'no_data': "no data found for this month.",
        'budget_set': "✅ budget set to {amount}€",
        'help': "you can write phrases like:\n- 'i spent 10€ for lunch at luigi's'\n- 'electricity bill 80€'\n- 'report'\n- 'set budget to 500€'",
        'error': "ops, something went wrong. please try again!",
    },
    'es': {
        'welcome': "¡hola {name}! soy tu asistente financiero. ¿cómo puedo ayudarte hoy?",
        'bill_reminder': "🔔 **¡recordatorio de pago!**\n\ndebes pagar: **{name}**\nimporte: **{amount}€**\nvencimiento: {due_date}\n\n¡usa /scadenze para gestionarlo!",
        'subscription_renewed': "🔄 **¡suscripción renovada!**\n\nhemos registrado il pago de **{amount}€** por **{name}**.",
        'session_expired': "la sesión ha expirado, inténtalo de nuevo.",
        'save_confirm_msg': "✅ **¡guardado!**\n{amount}€ por {desc}{budget_info}",
        'monthly_spent_label': "💰 gastado este mes: {total}€",
        'budget_left_label': "💰 quedan: {amount}€",
        'over_budget_alert': "🚨 **¡fuera de presupuesto!** (-{amount}€)",
        'save_error': "❌ error al guardar.",
        'ocr_saved_ok': "✅ ¡gasto de {amount}€ guardado correctamente!",
        'bill_set_ok': "📅 **¡recordatorio configurado!**\nte avisaré la mañana del {date}.",
        'sub_saved_ok': "✅ ¡suscripción a **{name}** guardada!",
        'sub_removed_ok': "🗑️ ¡suscripción eliminada de recurrentes!",
        'deleted_ok': "🗑️ ¡eliminado correctamente!",
        'bill_paid_ok': "✅ ¡factura '{name}' marcada como pagada y añadida a gastos!",
        'no_expenses_cat': "no hay gastos para {cat} este mes.",
        'detail_label': "detalle",
        'total_label': "total",
        'back_btn': "⬅️ volver a la lista",
        'reset_ok': "🧹 **¡base de datos limpia!**",
        'confirm_sub_btn': "✅ registrar suscripción",
        'confirm_bill_btn': "✅ configurar recordatorio",
        'sub_detected_msg': "💳 **nueva suscripción detectada**\n\n📌 servicio: **{name}**\n💰 cuota mensual: **{amount}€**\n🔄 renovación: cada **día {day}** del mes\n\n¿quieres registrarla?",
        'bill_detected_msg': "📅 **nuevo vencimiento detectado**\n\n📌 **{name}**\n💰 importe: **{amount}€**\n🗓️ vencimiento: **{date}**\n\n¿quieres un recordatorio?",
        'ai_understood': "esto es lo que he entendido:",
        'budget_warn_over': "\n⚠️ **atención:** ¡te has pasado del presupuesto por {amount}€!",
        'budget_residue': "\n💰 presupuesto restante: **{amount}€**",
        'transaction_preview': "💬 {ai_text}\n\n💰 **{amount}€** en {cat}\n📝 **concepto:** {desc}\n📅 total categoría: {cat_total}€{budget_info}",
        'error_understand': "⚠️ no te he entendido bien. intenta escribirlo más claro.",
        'no_expenses_month': "📭 no hay gastos registrados para {month}.",
        'list_expenses_title': "📂 **gastos de {month}**\nselecciona una categoría:",
        'parasite_report_alert': "📢 **¡chequeo mensual de suscripciones!**\n\nrevisa si sigues usando todo lo que pagas...",
        'stats_header': "📊 **informe mensual**",
        'stats_total_spent': "💸 total gastado: **{total}€**",
        'stats_subs_focus': "🧛 **enfoque en suscripciones:**\npagas **{count}** servicios por un total de **{total}€/mes**.",
        'no_subs_active': "✅ no tienes suscripciones activas.",
        'analyzing_data': "📊 analizando tus gastos...",
        'budget_remaining': "restante: **{amount}€**",
        'over_budget': "⚠️ **¡fuera de presupuesto!**",
        'report_caption': "📈 **tu informe mensual**",
        'chart_error': "no hay datos suficientes para el gráfico.",
        'help_text': "🤖 **guía rápida:**\n\n💰 **registrar gasto**: escribe '20 euros en mercadona' o 'pizza 15€'.\n📊 **/report**: genera un gráfico con el análisis de tus gastos.\n💬 **chat**: ¡puedes hablarme normalmente y te responderé!",
        'reset_warning': "⚠️ **¡atención!**\n¿estás seguro de querer borrar todos los gastos de este mes? esta acción no se puede deshacer.",
        'confirm_reset_btn': "✅ sí, borrar todo",
        'no_subs_hint': "📉 **no tienes suscripciones registradas.**\n\nprueba a decirme: 'suscripción netflix 12.99 el día 20'",
        'budget_set_ok': "🎯 **presupuesto mensual establecido:** {amount}€\n¡a partir de ahora el informe te mostrará cuánto te queda!",
        'budget_usage': "💡 usa: `/setbudget [cantidad]` (ej: `/setbudget 500`)",
        'delete_usage': "💡 usa: `/cancella [nombre]` (ej: `/cancella pizza`)",
        'no_results': "❓ no he encontrado nada para '{query}'.",
        'results_found': "🗑️ he encontrado {count} gastos. ¿cuáles quieres eliminar?",
        'delete_amount_btn': "🗑️ eliminar {amount}€",
        'generic_expense': "gasto",
        'voice_listening': "🎧 escuchando y transcribiendo...",
        'voice_empty': "⚠️ no he oído nada, inténtalo de nuevo.",
        'voice_understood': "📝 he entendido: \"{text}\"",
        'voice_error': "⚠️ lo siento, hubo un error al procesar el audio.",
        'ocr_processing': "📸 leyendo el ticket...",
        'ocr_error': "❌ no he podido leer el ticket.",
        'confirm_btn': "✅ confirmar y guardar",
        'cancel_btn': "🗑️ eliminar",
        'ocr_success_msg': "✅ **ticket analizado**\n\n💰 importe: **{amount}€**\n🛒 tienda: {merchant}\n📁 categoría: {category}\n📅 fecha: {date}\n\n¿quieres guardar este gasto?",
        'no_subs': "📉 no tienes suscripciones registradas en la base de datos.",
        'subs_title': "💳 **tus suscripciones activas:**",
        'day_label': "día",
        'monthly_total_label': "💸 total mensual: **{total}€**",
        'yearly_impact_label': "📅 impacto anual: **{total}€**",
        'delete_btn': "🗑️ eliminar {name}",
        'no_bills': "✨ ¡no tienes facturas pendientes por ahora!",
        'bills_title': "🗓️ **tus facturas activas:**",
        'delete_simple_btn': "🗑️ eliminar",
        'pay_btn': "✅ pagada",
        'bill_reminder': "⏰ **¡recordatorio de pago!**\n\n📌 factura: **{name}**\n💰 importe: **{amount}€**\n\n¿qué quieres hacer?",
        'inactivity_msg': "👀 **oye, ¿dónde te has metido?**\nno he registrado gastos en 48 horas. ¿tienes compras nuevas que contarme?",
        'weekly_report': "📅 **resumen semanal**\n\nen lo que va de mes has gastado: **{total}€**",
        'subscription_renewed': "🔄 **¡renovación automática!**\n\nhe registrado **{name}** ({amount}€).",
        'confirm_transaction': "¿confirmas {amount}€ en {category}?\n\n🏢 comercio: {merchant}\n📝 desc: {description}",
        'confirm_subscription': "¿quieres registrar la suscripción {name} de {amount}€?",
        'saved': "✅ ¡guardado correctamente!",
        'cancelled': "🗑️ operación cancelada.",
        'stats_msg': "📊 total de gastos de este mes: {total}€",
        'no_data': "no hay datos para este mes.",
        'budget_set': "✅ presupuesto fijado en {amount}€",
        'help': "puedes escribirme frases como:\n- 'he gastado 10€ en el almuerzo'\n- 'factura luz 80€'\n- 'informe'\n- 'fijar presupuesto en 500€'",
        'error': "vaya, algo ha salido mal. ¡inténtalo de nuevo!",
    },
    'fr': {
        'welcome': "salut {name} ! je suis ton assistant financier. comment puis-je t'aider aujourd'hui ?",
        'bill_reminder': "🔔 **rappel de facture !**\n\nvous devez payer : **{name}**\nmontant : **{amount}€**\néchéance : {due_date}\n\nutilisez /scadenze pour le gérer !",
        'subscription_renewed': "🔄 **abonnement renouvelé !**\n\nnous avons enregistré le paiement de **{amount}€** pour **{name}**.",
        'session_expired': "session expirée, réessaie.",
        'save_confirm_msg': "✅ **enregistré !**\n{amount}€ pour {desc}{budget_info}",
        'monthly_spent_label': "💰 dépensé ce mois-ci : {total}€",
        'budget_left_label': "💰 il reste : {amount}€",
        'over_budget_alert': "🚨 **hors budget !** (-{amount}€)",
        'save_error': "❌ erreur lors de l'enregistrement.",
        'ocr_saved_ok': "✅ dépense de {amount}€ enregistrée avec succès !",
        'bill_set_ok': "📅 **rappel configuré !**\nje t'informerai le matin du {date}.",
        'sub_saved_ok': "✅ abonnement à **{name}** enregistré !",
        'sub_removed_ok': "🗑️ abonnement supprimé des récurrences !",
        'deleted_ok': "🗑️ supprimé avec succès !",
        'bill_paid_ok': "✅ facture '{name}' marquée comme payée et ajoutée aux dépenses !",
        'no_expenses_cat': "aucune dépense pour {cat} ce mois-ci.",
        'detail_label': "détail",
        'total_label': "total",
        'back_btn': "⬅️ retour à la liste",
        'reset_ok': "🧹 **base de données nettoyée !**",
        'confirm_sub_btn': "✅ enregistrer l'abonnement",
        'confirm_bill_btn': "✅ configurer un rappel",
        'sub_detected_msg': "💳 **nouvel abonnement détecté**\n\n📌 service : **{name}**\n💰 frais mensuels : **{amount}€**\n🔄 renouvellement : chaque **jour {day}** du mois\n\nveux-tu l'enregistrer ?",
        'bill_detected_msg': "📅 **nouvelle échéance détectée**\n\n📌 **{name}**\n💰 montant : **{amount}€**\n🗓️ échéance : **{date}**\n\nveux-tu un rappel ?",
        'ai_understood': "voici ce que j'ai compris :",
        'budget_warn_over': "\n⚠️ **attention :** hors budget de {amount}€ !",
        'budget_residue': "\n💰 budget restant : **{amount}€**",
        'transaction_preview': "💬 {ai_text}\n\n💰 **{amount}€** en {cat}\n📝 **quoi :** {desc}\n📅 total catégorie : {cat_total}€{budget_info}",
        'error_understand': "⚠️ je n'ai pas bien compris. essaie d'écrire plus clairement.",
        'no_expenses_month': "📭 aucune dépense enregistrée pour {month}.",
        'list_expenses_title': "📂 **dépenses de {month}**\nsélectionne une catégorie :",
        'parasite_report_alert': "📢 **check-up mensuel des abonnements !**\n\nvérifie si tu utilises toujours tout ce que tu paies...",
        'stats_header': "📊 **rapport mensuel**",
        'stats_total_spent': "💸 total dépensé : **{total}€**",
        'stats_subs_focus': "🧛 **focus abonnements :**\ntu paies **{count}** services pour un total de **{total}€/mois**.",
        'no_subs_active': "✅ tu n'as pas d'abonnements actifs.",
        'analyzing_data': "📊 analyse de tes dépenses...",
        'budget_remaining': "restant : **{amount}€**",
        'over_budget': "⚠️ **hors budget !**",
        'report_caption': "📈 **ton rapport mensuel**",
        'chart_error': "données insuffisantes pour le graphique.",
        'help_text': "🤖 **guide rapide :**\n\n💰 **noter une dépense** : écris simplement '20 euros chez Monoprix' ou 'pizza 15€'.\n📊 **/report** : génère un graphique de tes dépenses.\n💬 **chat** : tu peux me parler normalement, je te répondrai !",
        'reset_warning': "⚠️ **attention !**\nes-tu sûr de vouloir supprimer toutes les dépenses de ce mois ? cette action est irréversible.",
        'confirm_reset_btn': "✅ oui, tout supprimer",
        'no_subs_hint': "📉 **aucun abonnement enregistré.**\n\nessaie de me dire : 'abonnement netflix 12.99 le 20 du mois'",
        'budget_set_ok': "🎯 **budget mensuel fixé :** {amount}€\ndésormais le rapport te montrera ce qu'il te reste !",
        'budget_usage': "💡 utilise : `/setbudget [montant]` (ex : `/setbudget 500`)",
        'delete_usage': "💡 utilise : `/cancella [nom]` (ex : `/cancella pizza`)",
        'no_results': "❓ je n'ai rien trouvé pour '{query}'.",
        'results_found': "🗑️ j'ai trouvé {count} dépenses. lesquelles veux-tu supprimer ?",
        'delete_amount_btn': "🗑️ supprimer {amount}€",
        'generic_expense': "dépense",
        'voice_listening': "🎧 j'écoute et je transcris...",
        'voice_empty': "⚠️ je n'ai rien entendu, réessaie.",
        'voice_understood': "📝 j'ai compris : \"{text}\"",
        'voice_error': "⚠️ désolé, une erreur est survenue lors du traitement audio.",
        'ocr_processing': "📸 lecture du ticket en cours...",
        'ocr_error': "❌ je n'ai pas pu lire le ticket.",
        'confirm_btn': "✅ confirmer et enregistrer",
        'cancel_btn': "🗑️ supprimer",
        'ocr_success_msg': "✅ **ticket analysé**\n\n💰 montant : **{amount}€**\n🛒 magasin : {merchant}\n📁 catégorie : {category}\n📅 date : {date}\n\nveux-tu enregistrer cette dépense ?",
        'no_subs': "📉 aucun abonnement enregistré dans la base de données.",
        'subs_title': "💳 **tes abonnements actifs :**",
        'day_label': "jour",
        'monthly_total_label': "💸 total mensuel : **{total}€**",
        'yearly_impact_label': "📅 impact annuel : **{total}€**",
        'delete_btn': "🗑️ supprimer {name}",
        'no_bills': "✨ tu n'as pas d'échéances en attente pour le moment !",
        'bills_title': "🗓️ **tes échéances actives :**",
        'delete_simple_btn': "🗑️ supprimer",
        'pay_btn': "✅ payée",
        'bill_reminder': "⏰ **rappel d'échéance !**\n\n📌 facture : **{name}**\n💰 montant : **{amount}€**\n\nque veux-tu faire ?",
        'inactivity_msg': "👀 **hé, où es-tu passé ?**\nje n'ai pas noté de dépenses depuis 48h. as-tu des achats à me signaler ?",
        'weekly_report': "📅 **résumé hebdomadaire**\n\njusqu'ici ce mois-ci, tu as dépensé : **{total}€**",
        'subscription_renewed': "🔄 **renouvellement automatique !**\n\nj'ai enregistré **{name}** ({amount}€).",
        'confirm_transaction': "confirmes-tu {amount}€ en {category} ?\n\n🏢 commerce : {merchant}\n📝 desc : {description}",
        'confirm_subscription': "veux-tu enregistrer l'abonnement {name} à {amount}€ ?",
        'saved': "✅ enregistré avec succès !",
        'cancelled': "🗑️ opération annulée.",
        'stats_msg': "📊 total des dépenses ce mois-ci : {total}€",
        'no_data': "aucune donnée trouvée pour ce mois.",
        'budget_set': "✅ budget fixé à {amount}€",
        'help': "tu peux m'écrire des phrases comme :\n- 'j'ai dépensé 10€ pour un déjeuner'\n- 'facture électricité 80€'\n- 'report'\n- 'fixer le budget à 500€'",
        'error': "oups, un problème est survenu. réessaie !",
    },
}

def get_text(key, lang='it', **kwargs):
    # se la lingua dell'utente non è supportata, usiamo l'inglese o l'italiano
    lang_map = lang if lang in STRINGS else 'en'
    text = STRINGS.get(lang_map, STRINGS['it']).get(key, STRINGS['it'][key])
    return text.format(**kwargs)